name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Apple workaround
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
    - name: Select Xcode
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    - name: Tests
      run: xcodebuild clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -scheme GitBlamePR -project GitBlamePR.xcodeproj
